/* ---------------------------------------------------------------------------
   Cost — LiteLLM spend, in a tab.

   This plugin holds no report logic. litellm-cost.sh queries the proxy and
   writes one standalone page into the app's static root; this frames it, says
   how old it is, and reloads it. The split is the point: the query needs a
   virtual key and the proxy's ledger, neither of which belongs in a browser,
   and the page is then useful on its own -- open /cost.html directly and it
   renders the same.

   An iframe rather than a shadow root, unlike the kit's retired Recent tab.
   That one rendered data it fetched as JSON, so inheriting the app's CSS
   variables through the shadow boundary was exactly right. This one displays a
   document that already carries its own stylesheet, and an iframe is the only
   boundary that keeps two stylesheets from meeting. The theme still follows the
   app: it is passed in the URL, because custom properties do not cross into a
   frame.

   LITELLM-SPECIFIC, AND STAYS IN THIS KIT -- see litellm-cost.sh.

   The host fetches this file, imports it from a blob: URL, and calls
   mount(container, api) when the tab is activated, unmount(container) when you
   navigate away. See https://cloudcli.ai/docs/plugin-overview
   --------------------------------------------------------------------------- */

/* The report is regenerated by a timer, so re-fetching more often than that
   only costs a request. Slow enough to be polite, quick enough that a tab left
   open does not go stale.                                                   */
const RELOAD_MS = 60 * 1000;
const REPORT_URL = '/cost.html';

const CSS = `
  :host { display: block; height: 100%; font-family: inherit; }
  .wrap { display: flex; flex-direction: column; height: 100%; min-height: 320px; }
  .bar {
    display: flex; align-items: center; gap: 10px;
    padding: 8px 12px; border-bottom: 1px solid var(--border, #262a31);
    font-size: 12px; color: var(--muted-foreground, #9aa1ac);
  }
  .bar .age { font-variant-numeric: tabular-nums; }
  .bar .spacer { flex: 1; }
  .bar button {
    font: inherit; color: inherit; cursor: pointer;
    padding: 4px 10px; border-radius: 6px;
    border: 1px solid var(--border, #262a31); background: transparent;
  }
  .bar button:hover { background: var(--accent, rgba(127,127,127,.15)); color: var(--accent-foreground, inherit); }
  .bar button:disabled { opacity: .5; cursor: default; }
  iframe { flex: 1; width: 100%; border: 0; background: var(--background, transparent); }
  .miss { padding: 24px; font-size: 13px; line-height: 1.6; color: var(--foreground, inherit); }
  .miss code {
    display: block; margin-top: 10px; padding: 8px 10px; border-radius: 6px;
    background: var(--muted, rgba(127,127,127,.12));
    font-family: ui-monospace, SFMono-Regular, monospace; font-size: 12px;
  }
`;

/* Dark or light, as the app currently is. The report reads this from its URL
   because CSS custom properties do not cross an iframe boundary.           */
const currentTheme = () =>
  document.documentElement.classList.contains('dark') ||
  document.documentElement.dataset.theme === 'dark'
    ? 'dark'
    : 'light';

const ageText = (generatedAt) => {
  if (!generatedAt) return 'age unknown';
  const seconds = Math.max(0, Math.round((Date.now() - generatedAt.getTime()) / 1000));
  if (seconds < 90) return `generated ${seconds}s ago`;
  const minutes = Math.round(seconds / 60);
  if (minutes < 90) return `generated ${minutes}m ago`;
  return `generated ${Math.round(minutes / 60)}h ago`;
};

/* The page stamps its own generation time; Last-Modified would report when the
   file was written, which is the same thing until a write fails and the old
   file stays put. Reading the stamp means a stale report cannot look fresh. */
const readStamp = (html) => {
  const match = html.match(/generated <b>([\d-]+ [\d:]+) UTC<\/b>/);
  if (!match) return null;
  const parsed = new Date(match[1].replace(' ', 'T') + 'Z');
  return Number.isNaN(parsed.getTime()) ? null : parsed;
};

function build(root) {
  const shadow = root.attachShadow({ mode: 'open' });
  const style = document.createElement('style');
  style.textContent = CSS;
  const wrap = document.createElement('div');
  wrap.className = 'wrap';
  wrap.innerHTML = `
    <div class="bar">
      <span class="age">loading…</span>
      <span class="spacer"></span>
      <button type="button" data-reload>Reload</button>
    </div>
    <!-- Not sandboxed, deliberately: the framed page is one this kit writes into
         the app's own static root, and it needs its own script to read the theme
         out of its URL. Everything the proxy supplies -- key aliases, model
         names, the account email, an error message -- is HTML-escaped by
         litellm-cost.sh before it reaches the page, so the only code in there is
         the code the kit put there. -->
    <iframe title="LiteLLM spend report"></iframe>
  `;
  shadow.append(style, wrap);

  const age = wrap.querySelector('.age');
  const button = wrap.querySelector('[data-reload]');
  const frame = wrap.querySelector('iframe');
  let generatedAt = null;
  let timer = null;

  const missing = (status) => {
    frame.remove();
    const note = document.createElement('div');
    note.className = 'miss';
    note.innerHTML =
      status === 404
        ? 'No report yet. It is written by <b>litellm-cost.sh</b>, which the launcher ' +
          'runs at start and the timer runs every few minutes:<code>~/bin/cloudcli-cost</code>'
        : `Could not load the report (HTTP ${status}).<code>~/bin/cloudcli-cost</code>`;
    wrap.append(note);
    age.textContent = 'no report';
    button.disabled = true;
  };

  /* Fetched rather than pointed at, so the age can be read from the page and a
     missing file explained instead of showing the app's 404.               */
  const load = async () => {
    button.disabled = true;
    try {
      const response = await fetch(`${REPORT_URL}?t=${Date.now()}`, { cache: 'no-store' });
      if (!response.ok) {
        missing(response.status);
        return;
      }
      const html = await response.text();
      generatedAt = readStamp(html);
      age.textContent = ageText(generatedAt);
      frame.src = `${REPORT_URL}?theme=${currentTheme()}&t=${Date.now()}`;
    } catch (error) {
      age.textContent = `load failed: ${error?.message || error}`;
    } finally {
      button.disabled = false;
    }
  };

  button.addEventListener('click', load);
  timer = window.setInterval(() => {
    age.textContent = ageText(generatedAt);
    void load();
  }, RELOAD_MS);

  void load();

  return {
    destroy() {
      if (timer !== null) window.clearInterval(timer);
      timer = null;
    },
  };
}

/* The host hands the same container to mount and unmount, and re-imports this
   module per mount, so the instance is parked on the element itself rather than
   in module scope.                                                          */
export async function mount(container, host) {
  const root = document.createElement('div');
  root.style.height = '100%';
  container.replaceChildren(root);
  container.__kitCost = build(root, host);
}

export function unmount(container) {
  container.__kitCost?.destroy();
  delete container.__kitCost;
  container.replaceChildren();
}
